export const CREATE_VACCINE_APPOINTMENT = "CREATE_VACCINE_APPOINTMENT";
export const CREATE_VACCINE_APPOINTMENT_SUCCESS =
  "CREATE_VACCINE_APPOINTMENT_SUCCESS";
export const CREATE_VACCINE_APPOINTMENT_FAILED =
  "CREATE_VACCINE_APPOINTMENT_FAILED";

export const GET_SCHEDULED_VACCINATION_CENTRES_BY_INFO =
  "GET_SCHEDULED_VACCINATION_CENTRES_BY_INFO";
export const GET_SCHEDULED_VACCINATION_CENTRES_BY_INFO_SUCCESS =
  "GET_SCHEDULED_VACCINATION_CENTRES_BY_INFO_SUCCESS";
export const GET_SCHEDULED_VACCINATION_CENTRES_BY_INFO_FAILED =
  "GET_SCHEDULED_VACCINATION_CENTRES_BY_INFO_FAILED";

export const GET_VACCINE_APPOINTMENTS_BY_INFO =
  "GET_VACCINE_APPOINTMENTS_BY_INFO";
export const GET_VACCINE_APPOINTMENTS_BY_INFO_SUCCESS =
  "GET_VACCINE_APPOINTMENTS_BY_INFO_SUCCESS";
export const GET_VACCINE_APPOINTMENTS_BY_INFO_FAILED =
  "GET_VACCINE_APPOINTMENTS_BY_INFO_FAILED";

export const GET_VACCINATION_CENTRE_BY_ID = "GET_VACCINATION_CENTRE_BY_ID";
export const GET_VACCINATION_CENTRE_BY_ID_SUCCESS =
  "GET_VACCINATION_CENTRE_BY_ID_SUCCESS";
export const GET_VACCINATION_CENTRE_BY_ID_FAILED =
  "GET_VACCINATION_CENTRE_BY_ID_FAILED";

export const GET_VACCINE_APPOINTMENTS_BY_CREATED_BY =
  "GET_VACCINE_APPOINTMENTS_BY_CREATED_BY";
export const GET_VACCINE_APPOINTMENTS_BY_CREATED_BY_SUCCESS =
  "GET_VACCINE_APPOINTMENTS_BY_CREATED_BY_SUCCESS";
export const GET_VACCINE_APPOINTMENTS_BY_CREATED_BY_FAILED =
  "GET_VACCINE_APPOINTMENTS_BY_CREATED_BY_FAILED";

export const GET_VACCINATION_BY_NIC = "GET_VACCINATION_BY_NIC";
export const GET_VACCINATION_BY_NIC_SUCCESS = "GET_VACCINATION_BY_NIC_SUCCESS";
export const GET_VACCINATION_BY_NIC_FAILED = "GET_VACCINATION_BY_NIC_FAILED";
