export const GET_PATIENTS_OVERALL_STATS = "GET_PATIENTS_OVERALL_STATS";
export const GET_PATIENTS_OVERALL_STATS_SUCCESS =
  "GET_PATIENTS_OVERALL_STATS_SUCCESS";
export const GET_PATIENTS_OVERALL_STATS_FAILED =
  "GET_PATIENTS_OVERALL_STATS_FAILED";

export const GET_PATIENTS_BY_GUARDIAN = "GET_PATIENTS_BY_GUARDIAN";
export const GET_PATIENTS_BY_GUARDIAN_SUCCESS =
  "GET_PATIENTS_BY_GUARDIAN_SUCCESS";
export const GET_PATIENTS_BY_GUARDIAN_FAILED =
  "GET_PATIENTS_BY_GUARDIAN_FAILED";
