export const CREATE_TEST_APPOINTMENT = "CREATE_TEST_APPOINTMENT";
export const CREATE_TEST_APPOINTMENT_SUCCESS =
  "CREATE_TEST_APPOINTMENT_SUCCESS";
export const CREATE_TEST_APPOINTMENT_FAILED = "CREATE_TEST_APPOINTMENT_FAILED";

export const GET_SCHEDULED_TEST_CENTRES_BY_INFO =
  "GET_SCHEDULED_TEST_CENTRES_BY_INFO";
export const GET_SCHEDULED_TEST_CENTRES_BY_INFO_SUCCESS =
  "GET_SCHEDULED_TEST_CENTRES_BY_INFO_SUCCESS";
export const GET_SCHEDULED_TEST_CENTRES_BY_INFO_FAILED =
  "GET_SCHEDULED_TEST_CENTRES_BY_INFO_FAILED";

export const GET_TEST_APPOINTMENTS_BY_INFO = "GET_TEST_APPOINTMENTS_BY_INFO";
export const GET_TEST_APPOINTMENTS_BY_INFO_SUCCESS =
  "GET_TEST_APPOINTMENTS_BY_INFO_SUCCESS";
export const GET_TEST_APPOINTMENTS_BY_INFO_FAILED =
  "GET_TEST_APPOINTMENTS_BY_INFO_FAILED";

export const GET_TEST_CENTRE_BY_ID = "GET_TEST_CENTRE_BY_ID";
export const GET_TEST_CENTRE_BY_ID_SUCCESS = "GET_TEST_CENTRE_BY_ID_SUCCESS";
export const GET_TEST_CENTRE_BY_ID_FAILED = "GET_TEST_CENTRE_BY_ID_FAILED";

export const GET_TEST_APPOINTMENTS_BY_CREATED_BY =
  "GET_TEST_APPOINTMENTS_BY_CREATED_BY";
export const GET_TEST_APPOINTMENTS_BY_CREATED_BY_SUCCESS =
  "GET_TEST_APPOINTMENTS_BY_CREATED_BY_SUCCESS";
export const GET_TEST_APPOINTMENTS_BY_CREATED_BY_FAILED =
  "GET_TEST_APPOINTMENTS_BY_CREATED_BY_FAILED";
